# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

roll_vector_nas <- function(x) {
    .Call('LargeDataCppFunctions_roll_vector_nas', PACKAGE = 'LargeDataCppFunctions', x)
}

subsetCpp <- function(data, indxs) {
    .Call('LargeDataCppFunctions_subsetCpp', PACKAGE = 'LargeDataCppFunctions', data, indxs)
}

getSubsetSplit <- function(Dsexp, split_idx, beg_index, end_index, fun) {
    .Call('LargeDataCppFunctions_getSubsetSplit', PACKAGE = 'LargeDataCppFunctions', Dsexp, split_idx, beg_index, end_index, fun)
}

getSplitIndexes <- function(Dsexp, split_row_name) {
    .Call('LargeDataCppFunctions_getSplitIndexes', PACKAGE = 'LargeDataCppFunctions', Dsexp, split_row_name)
}

Lapply <- function(data, fun) {
    .Call('LargeDataCppFunctions_Lapply', PACKAGE = 'LargeDataCppFunctions', data, fun)
}

getChunksIndexesForSplitList <- function(data_, split_indx, chk_size) {
    .Call('LargeDataCppFunctions_getChunksIndexesForSplitList', PACKAGE = 'LargeDataCppFunctions', data_, split_indx, chk_size)
}

